#!/usr/bin/env sh

#  Copyright (c)  Alex Genovese   https://github.com/qqxproject

#  THIS SCRIPT SHOULD BE RUN FROM INSIDE THE qqX DOWNLOAD/SOURCE FOLDER, where it will expect to find the right files
#  OR  run the target script "./qqX_system_install"  from qqX.system folder directly

#  From version 1.10.03  A POSIX FRIENDLY .sh SCRIPT is USED AS A WRAPPER, to make sure that it double click executes properly
#  in Qt / KDE XFCE etc desktop environments.

  #########################################################################################################################################

#   IF your FILE MANAGER allows:

#   Double mouse click  >  'run in terminal' or 'execute' ....

#   or     Right click  >  'run as program'  or 'run in terminal'  or 'run in konsole' ....

#   or  Right click on Folder  >  'open in TERMINAL'  and  type "./qqX_setup_and_install"   (click on folder, not file, also note prefix ./)

  #########################################################################################################################################

#   FOR ANY NEWER OR NON-STANDARD TERMINAL, setting up a CUSTOM TERMINAL-PROFILE is recommended
#   as this will allow the values to be stored for future updates:

#   See notes in the system script "./qqX_system_install" in the folder "qqX.system",
#   just after the initial checking lines, for 'CustomTerminalProfile=' at around line 300

#   shellcheck disable=SC2009,SC2034

#   Terminal name may also be set here, for one-time usage, if '-e' exec functions are recognised:
    UserTerm=

#########################################################################################################################################

## SELECTION OF TERMINAL:

# Priority is given to main stream user bases and those offering geometry parameters

# At the beginning of 2026, 'qterminal' and' mate-terminal' are now being generally RECOMMENDED for qqX as they are
# both lightweight and can both be easily installed as alternatives on almost any desktop or window manager, either X11 or Wayland

# In 2024, 85% of users were probably covered by the first four: "gnome-terminal" "konsole" "mate-terminal" "xfce4-terminal"
# Over 95% probably when "qterminal" and "alacritty" were added.
# At 08/2025 a kgx check was included as some Gnome distros were using 'Gnome Console' aka 'kgx' as an alias call for Gnome Terminal ....

# There are also several popular post-install terminals with various special feature sets.
# However, it is very unlikely to find any of these alone and an underlying standard desktop environment terminal
# can generally be expected to be available:
#
# Kitty, in 2024 was relatively stable and had a more or less standard behaviour, so it was added for good measure.
#
# On the other hand, many other leading edge, often cross-platform terminals were/are still in active development
# and are liable to change. We need to view these as unstable BUT development should be encouraged and revisits made.
#
# Wezterm @ 01/2026, for example, has much potential. Its command line is now less idiosyncratic than two years ago,
# but it now has 50% more open issues, now nearly 1,400 with which to contend ...
#
# The advent of Wayland has also seen other projects have being abandoned completely.
# Termite, for example, now encourages the use of Alacritty ...

# Users with Window Managers, not Desktop Envs will be familiar with terminals and settings at the cmd line
# However add some well known interfaces where possible, eg. urxvt that comes with 'i3' as this helps with running of QF

#########################################################################################################################################

# This terminal check list also needs to be available for the standard upgrader script:
if [ "$1" = "MakeTermList" ]; then MakeTermList=1 ; shift ; else MakeTermList= ; fi

printf "" > "/tmp/qqX.termlist"
if [ -n "$UserTerm" ]; then  printf "%s\n" "$UserTerm" > "/tmp/qqX.termlist"
fi

# Use 'set' to make an array of usable terminals
# See https://stackoverflow.com/questions/35385962/arrays-in-a-posix-compliant-shell#59353917
set -- "gnome-terminal" "konsole" "mate-terminal" "xfce4-terminal" "qterminal" "lxterminal" "roxterm" "urxvt" "uxterm" "xterm"
set -- "$@" "ptyxis" "kgx" "alacritty" "kitty" "foot"

# Check through the array and output a list of those possibly found, using 'command -v'  (not 'type -p' which is Bash)
while [ -n "$1" ] ; do
  if [ -n "$(command -v "$1")" ] ; then printf "%s\n" "$1" >> "/tmp/qqX.termlist"
  fi
  shift
done

if [ -n "$MakeTermList" ]; then exit ; fi

# NB: edits here, can impact on '$Terminal_Start' in disk maintenance script (qf function)
# Also see exception handling: 'TERMINAL not found or not suitable' towards end of script

# Priority listing should have placed the top entry as being the most main stream and being one with sufficient size.
# At this stage we are just looking for something reliable to run the actual terminal selection script.
if [ -n "$(cat "/tmp/qqX.termlist")" ]; then UserTerm="$(head -n 1 "/tmp/qqX.termlist")"
fi

# If there is still nothing, try a barrel scrape for something running that might have 'term' in the name ...
if [ -z "$UserTerm" ]; then TermGrep="$(pgrep -a term | grep qqX | tr -cd '[:print:]' | awk '{print $2}')"
  if [ -n "$TermGrep" ]; then UserTerm="$(basename "$TermGrep")"
  fi
fi

# 10/2025 ptyxis resolved, hopefully, from ver 49.1 (tested on Fedora 43 beta)

if [ -z "$UserTerm" ] && [ -n "$(command -v = "cosmic-term")" ] ; then
  printf "\n\n  The new COSMIC terminal 'cosmic-term' has been detected on this system, "
  printf "\n  however, at 12/2025 it is unfortunately problematic."
  printf "\n\n  Luckily, systems are fine with more than one terminal installed and present:"
  printf "\n\n  Recommended general installations are 'mate-terminal' or 'qterminal'"
  printf "\n  which are both lightweight and Wayland/X11/multi-DE compatible."
  printf "\n\n  If you wish to force cosmic-term, to see if changes make it now possible to use,"
  printf "\n  edit the entry for 'UserTerm' at the start of this script, and re-run."
  printf "\n\n  [enter] to quit, install another terminal and retry"
  printf "\n\n  >  "
  read -r  REPLY
  exit
fi

DefWidth=150
DefHeight=45

if [ "$UserTerm" = "kgx" ]; then
  "$UserTerm" --wait -- "./qqX.system/qqX_system_install"
elif [ "$UserTerm" = "gnome-terminal" ]; then
  if gnome-terminal --help-window-options 2>/dev/null | grep -qs geometry ; then
    "$UserTerm" --geometry ${DefWidth}x${DefHeight} --wait -- "./qqX.system/qqX_system_install"
  else
    UserTerm="kgx"
    "$UserTerm" --wait -- "./qqX.system/qqX_system_install"
  fi
elif [ "$UserTerm" = "konsole" ]; then
  "$UserTerm" --hide-menubar --hide-tabbar --notransparency -p TerminalColumns=145 -p TerminalRows=50  -e  "./qqX.system/qqX_system_install"

elif [ "$UserTerm" = "mate-terminal" ]; then
  "$UserTerm" --geometry=145x50 --hide-menubar -e "./qqX.system/qqX_system_install"

elif [ "$UserTerm" = "xfce4-terminal" ]; then
  "$UserTerm" --geometry=145x50 --hide-menubar --hide-toolbar  -e "./qqX.system/qqX_system_install"

elif [ "$UserTerm" = "qterminal" ]; then
  # create profile for geometry
  if [ -e "$HOME/.config/qterminal.org/qterminal.ini" ]; then
    TermConf_User="$HOME/.config/qterminal.org/qterminal.ini"
    TermConf_Tmp="/tmp/qq-qterminal.ini"
    # sed -i is not always present, use grep.
    # But not 'grep -i' as lower case 'size=@' is separate from other camelCase entries with *Size=@
    grep -B 500 'size=@' "$TermConf_User" | head -n -1 > "$TermConf_Tmp"
    echo "size=@(1200 600)" >> "$TermConf_Tmp"
    grep -A 500 'size=@' "$TermConf_User" | tail -n +2 >> "$TermConf_Tmp"
    "$UserTerm" -p "$TermConf_Tmp" -e "./qqX.system/qqX_system_install"
  else
    "$UserTerm" -e "./qqX.system/qqX_system_install"
  fi

elif [ "$UserTerm" = "alacritty" ]; then
  # create profile for geometry
  if [ -e "$HOME/.config/alacritty/alacritty.toml" ]; then
    TermConf_User="$HOME/.config/alacritty/alacritty.toml"
    TermConf_Tmp="/tmp/qq-alacritty.toml"
    # sed -i is not always present, use grep.
    grep -B 500 'window.dimensions' "$TermConf_User" > "$TermConf_Tmp"
    { echo "columns = 150" ; echo "lines = 45"; } >> "$TermConf_Tmp"
    grep -A 500 'window.dimensions' "$TermConf_User" | tail -n +4 >> "$TermConf_Tmp"
    "$UserTerm" --config-file "$TermConf_Tmp" -e "./qqX.system/qqX_system_install"
  else
    "$UserTerm" -e "./qqX.system/qqX_system_install"
  fi

elif [ "$UserTerm" = "lxterminal" ] || [ "$UserTerm" = "roxterm" ]; then
  "$UserTerm" --geometry=145x50 -e "./qqX.system/qqX_system_install"

elif [ "$UserTerm" = "urxvt" ]; then
  "$UserTerm" -e "./qqX.system/qqX_system_install"

elif [ "$UserTerm" = "uxterm" ] || [ "$UserTerm" = "xterm" ]; then
  "$UserTerm" -geometry 145x50 -fa truetype -fs 12 -fg white -bg black -e "./qqX.system/qqX_system_install"

# A popular (and cross-platform) choice for lightweight Wayland is Alacritty, which is higher up the 'set' list.

elif [ "$UserTerm" = "kitty" ] ; then
  # Unlikely to be a primary terminal but added as is quite popular, especially with cross-platform users.
  "$UserTerm"  "./qqX.system/qqX_system_install"

elif [ "$UserTerm" = "foot" ] ; then
    # FOO Terminal is a lightweight terminal starting to appear in places for Wayland
    # but @ 2024 tests have shown it to throw trivial warnings when switching shells,
    # hence the '2>/dev/null' and placement (for now) towards the end
  "$UserTerm"  "./qqX.system/qqX_system_install"  2>/dev/null

# elif [ "$UserTerm" = "wezterm" ] ; then
  #"$UserTerm" start --cwd "$(pwd)" -- "./qqX.system/qqX_system_install"
  # @ 01/2026 now accepts '-e' as an alias for 'start' and may not now need the '--cwd'
  # See https://wezterm.org/cli/general.html#synopsis  But still has lots of open issues ...  # REVIEW

elif [ -n "$UserTerm" ]; then
  # Standard start for unknown possibilities, size params not used:
  # Terminals will normally accept '-e' even if it is not the preferred method  # REVIEW
  "$UserTerm" -e "./qqX.system/qqX_system_install"

elif [ -t 1 ] ; then
  # Probably 97 to 100% chance of finding the matching desktop environment default terminal.
  # If none found, where possible, if stdout is available, give help message.
  # https://stackoverflow.com/a/911213
  printf "\n\n   TERMINAL NOT SUITABLE or not found:"

  printf "\n\n   Recommended general installations are 'mate-terminal' or 'qterminal'"
  printf "\n   which are both lightweight and Wayland/X11/multi-DE compatible."
  printf "\n\n   Systems are fine with more than one terminal installed and present ..."

  printf "\n\n   Try: sudo apt install (or dnf install, pacman -Syu, etc) mate-terminal "

  # show the help notes at top of script
  printf "\n\n\n   Pre-Configured and possibly installable terminals include:"
  printf "\n\n"
  grep -e ^set "$0"| cut -d'-' -f 3- | tr ' ' '\n' | grep -v '@' | grep '"' | paste -s -d ' ' | fmt -w 90
  if [ -n "$(command -v "flatpak")" ] ; then
    printf "\n\n  Unfortunately, Flatpak installed terminals are currently problematic"
    printf "\n\n  including a possible qqX flatpak ...."
  fi
  printf "\n\n\n"
  #grep -m 1 -A 4 'FOR ANY NEWER' "$0"
  printf "  See notes at script start for custom terminal-profiles"
  printf "\n\n  [enter] to exit and configure ...\n\n    "
  read -r reply
fi

if [ -t 1 ] ; then
  if [ -n "$UserTerm" ]; then
    printf "\n"
    printf "\n\n   qqX startup installer initially running in:  %s"  "$UserTerm"
  fi
  printf "\n"
  printf "\n\n   Help and info always available at https://qqxproject.org/"
  printf "\n"
  printf "\n\n   Your terminal or distro/terminal combination may need, or may have needed "
  printf "\n\n   this window to stay open until qqX has completed its tasks ..."
  printf "\n"
  printf "\n\n   [enter] to close \n\n  "
  read -r reply
fi

# Exit the script. But also check whether it has been run with a --hold optioned terminal, as Dolphin does, for example.
PidRun="$(ps -eF | grep sh | grep "$$" | grep "$0" | tr -cd '[:print:]' | awk '{print $3}')"

# Needs SIGHUP in KDE or logs out of desktop session... See https://en.wikipedia.org/wiki/Signal_(IPC)#Handling_signals
if [ -n "$PidRun" ]; then  kill -s 1 "$PidRun"
else exit
fi

# Licence  GPL3   https://www.gnu.org/licenses

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# https://www.gnu.org/licenses

# IF CODE IN GENERAL BECOMES USED IN ANY OTHER PROJECT,
# THE GPL3 LICENCE APPLIES & YOU SHOULD SHOW CLEAR ATTRIBUTIONS.

# But, that said, and without prejudice to the above,
# SMALL CODE SNIPPETS, eg the function printColor, MAY BE USED PERMISSIVELY
# in projects, as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.

# qqX - quickemu quickget X terminal project

# https://code.visualstudio.com/  (recommended)
# vim:tabstop=2:shiftwidth=2:expandtab
