#!/usr/bin/env bash

##  qqX component to be located in folder 'qqX.main'

##  Copyright (c)  Alex Genovese   https://github.com/qqxproject
#   SMALL CODE SNIPPETS eg the function printColor MAY BE USED
#   PERMISSIVELY in projects as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.
# 	Otherwise:
#   Licence  GPL3   https://www.gnu.org/licenses
##  qqX - quickemu quickget X terminal project

## ShellCheck global disables:
# https://www.shellcheck.net/wiki/SC2242 as it clashes with use of exit traps used to keep mouse click scripts open
# And SC1090,SC1091,SC2024, SC2154 for necessity of dynamic file sourcing

#  shellcheck disable=SC2242,SC1090,SC1091,SC2034,SC2154

# Tries to make sure that all current processes have been statted properly and that conlflicts are not there
# Standard command line Qemu (and Quickemu) likes one VM at a time
# Otherwise, libvirt/virsh is needed, and things no longer stay relatively simple ...

# 2026 changes to the way Gnome and KDE run have complicated process tracing,
# in particular with Gnome where the replacement gnome-terminal 'ptyxis' is still finding its feet.
# From ptyxis version 50.1 onwards we are seeing the WiP dust as somewhat settled but we are still
# unable to boot with window size presets ...

# Different terminals now use different process controls:
# Ptyxis and Konsole will issue new shared (grand)parents for every window, and gnome now uses an intermediary 'ptyxis-agent'
# whereas mate-terminal and qterminal will route all windows through the same parent ...

# To resolve this 2026 dilemma, the instance checker has now been sharded off into its own script
# and the idea of tagging each window/session start with a time based unique identifier has been introduced

# Run once:

qqX_SessionID="$(uuidgen -7)"
qqX_SessionFile="/tmp/qqX_session_$qqX_SessionID"
printf '#!/bin/bash' > "$qqX_SessionFile"
chmod +x "$qqX_SessionFile"

if [[ $ShowProcesses ]]; then
  printf "\n\n General Script 'MULTI_INSTANCE_CHECKS' > "
  printf "\n\n qqX_SessionID  %s" "$qqX_SessionID"
  printf "\n\n\n    PRE find pid/ppid > pgrep -afi '/qqX' > \n\n"
  pgrep -afi '/qqX'
fi

sleep 0.2
MultiQuit= ; KillQQ= ; AnotherQQ=
CurrentQQ_FullLine= ; CurrentQQ_LastField= ; CurrentQQ= ; CurrentQQ_Parent= ; CurrentQQ_GrandParent=
CurrentQQ_GrandParentText= ; CurrentQQ_SharedGrandParent= ; CurrentQQ_SharedGrandParentText=

CurrentQQ="$$"
# shellcheck disable=SC2016
{ printf "\n\nCurrentQQ=\"%s\"\n\n" "$CurrentQQ"
printf 'while [[ $(ps --no-header -f "$CurrentQQ" 2>/dev/null) ]]; do sleep 1 ; done'
printf "\n\n"
} >> "$qqX_SessionFile" &
wait "$!"
# script autostops when parent finishes whilst the instance checker ignores scripts that are not running
# and any unneeded tmp files will get dropped soon enough
# set background ID process running:
"$qqX_SessionFile" &

CurrentQQ_FullLine="$(ps --no-header -f "$$")"
if [[ "$CurrentQQ_FullLine" != *'/qqX' ]]; then
  CurrentQQ_Input="$(awk '{print $NF}' <<< "$CurrentQQ_FullLine")"
else CurrentQQ_Input=
fi
CurrentQQ_Parent="$(ps --no-header -fo ppid "$CurrentQQ" | tr -cd '[:digit:]')"
CurrentQQ_Parent_FullLine="$(ps --no-header -f "$CurrentQQ_Parent")"
CurrentQQ_GrandParent="$(ps --no-header -fo ppid "$CurrentQQ_Parent" | tr -cd '[:digit:]')"
CurrentQQ_SharedGrandParent="$(ps --no-header -fo ppid "$CurrentQQ_GrandParent" | tr -cd '[:digit:]')"
CurrentQQ_GrandParentText="$(ps -f --no-header "$CurrentQQ_Parent")"
CurrentQQ_SharedGrandParentText="$(ps -f --no-header "$CurrentQQ_GrandParent")"

# track any starts made via KDE dolphin as simple exits are not possible in these cases
DolphinExitPid="$(pgrep -fa "$0" | grep -s konsole | grep -e '--hold' | awk '{print $1}' 2>/dev/null)"

if [[ $ShowProcesses ]]; then
  [[ $CurrentQQ ]] && printf "\n    CurrentQQ \$\$ = %s" "$CurrentQQ"
  [[ $CurrentQQ_FullLine ]] && printf "\n\n    CurrentQQ_FullLine ps -f \$\$ '%s'" "$CurrentQQ_FullLine"
  if [[ $CurrentQQ_Input ]]; then printf "\n\n    CurrentQQ_Input = %s" "$CurrentQQ_Input"
  else  printf "\n\n    CurrentQQ_Input = no specific targets"
  fi
  [[ $UserTerm ]] && printf "\n\n    UserTerm = %s" "$UserTerm"
  [[ $DolphinExitPid ]] && printf "\n\n    DolphinExitPid = %s" "$DolphinExitPid"
  [[ $CurrentQQ_Parent_FullLine ]] && printf "\n\n    CurrentQQ_Parent_FullLine = %s" "$CurrentQQ_Parent_FullLine"
  [[ $CurrentQQ_Parent ]] && printf "\n\n    CurrentQQ_Parent = %s" "$CurrentQQ_Parent"
  [[ $CurrentQQ_GrandParent ]] && printf "    CurrentQQ_GrandParent = %s" "$CurrentQQ_GrandParent"
  [[ $CurrentQQ_SharedGrandParent ]] && printf "    CurrentQQ_SharedGrandParent = %s \n\n" "$CurrentQQ_SharedGrandParent"
  [[ $CurrentQQ_GrandParentText ]] && printf "    CurrentQQ_GrandParentText = '%s' \n\n" "$CurrentQQ_GrandParentText"
  [[ $CurrentQQ_SharedGrandParentText ]] && printf "    CurrentQQ_SharedGrandParentText = '%s' \n\n" "$CurrentQQ_SharedGrandParentText"
  printf "\n\n    POST find pid/ppid > pgrep -afi '/qqX' > \n\n"
  pgrep -afi '/qqX'
fi

# Re-checkable:

function multi_instance_checks {

  while true; do

    # NOTE use 'ps' here as pgrep can cause problems  (plus ignore any root process history from installer or copy-over)
    # pgrep -an is not reliable and pgrep sub-shell creates another pid too ...

    # shellcheck disable=SC2009
    AnotherQQ="$(ps -ef | grep -e '/qqx' -e '/qqX' | grep -e ^"$USER" | grep -v 'qqX_copy_over' | grep -v 'qqX/tags' | grep -v '_install' \
    | grep -v -e 'code/code' | grep -v -e 'lib/fv' | grep -v qqxproject | grep -v grep  2>/dev/null)"

    # If loading up the qcow menu, but then not choosing the qf option,
    # then the currrent qcow ceases to be a duplicate, and we need the VM selector interface, not the main selected one
    if [[ $Trace_InputVars ]]; then
      printf "\n\n Chrome up: Positional Vars = %s" "$*"
      printf "\n\n QF_exit_to_Main is %s" "$QF_exit_to_Main"
      printf "\n\n XDG_MimeType_Recognised is %s" "$XDG_MimeType_Recognised"
      printf "\n\n XDG_MimeType_is_ISO is %s" "$XDG_MimeType_is_ISO"
      printf "\n\n XDG_MimeType_is_QCOW is %s" "$XDG_MimeType_is_QCOW"
      printf "\n\n XDG_Input_NON_qqX is %s \n\n" "$XDG_Input_NON_qqX"
      echo " pwd  $(pwd)"
      echo; sleep "$Trace_InputVars"
    fi

    # CL launched running of qcow2 file management happens before this script is called. See qqX start.
    # Running CL instances will show up with 'pgrep -aAxi qqX' as 'pid /bin/bash /usr/bin/qqX --qqf' or similar
    # With pgrep -afi qqX_filemanage as: pid /bin/bash /usr/share/qqX/qqX.main/qqX_filemanage_qcow_drive --qqf

    if [[ $ShowProcesses ]]; then
      echo; echo " AnotherQQ String List:"; [[ $AnotherQQ ]] && printf "\n%s" "$AnotherQQ"
      printf "\n\n QF_exit_to_Main = %s \n\n" "$QF_exit_to_Main"
    fi

    # Starting Main via the .qcow2 route needs to counted too. And only 1 QF instance should exist.
    # .qcow2 remains when 'exit to main' but changes to 'filemanage' when switching to QF
    # Plus while elif [[ "$QQ" == *'.qcow2'* ]]; gets included in [[ "$QQ" != *'qqX_copy_over'* ]]

    CurrentQQ_mode="main"
    if [[ ! $QF_exit_to_Main ]]; then
      # qcow, in the sense of manage a qcow disk, not just use one trigger a main menu ...
      case "$CurrentQQ_LastField" in
        *'.qcow2'*|*'--qqf'*|*'qqX_filemanage '*) CurrentQQ_mode="qcow" ;;
      esac
    fi

  if [[ $AnotherQQ ]]; then
      # NB: awk '{print $1}' for pgrep and awk '{print $2}' for ps
      OtherQQ_MainArr=()
      OtherQQ_qqF_Arr=()
      mapfile -t AnotherQQ_Arr <<< "$AnotherQQ"
      for QQ in "${AnotherQQ_Arr[@]}"; do
        [[ "$QQ" == *"$CurrentQQ"* ]] && [[ "$QQ" == *"$CurrentQQ_Parent"* ]] && continue
      [[ $ShowProcesses ]] && printf "\n Awk \$3 %s (process parent) matches Current process or Parents ++ ?? \n" "$(awk '{print $3}' <<< "$QQ")"
        [[ $CurrentQQ ]] && [[ $(awk '{print $3}' <<< "$QQ") == "$CurrentQQ" ]] && continue
        [[ $CurrentQQ_Parent ]] && [[ $(awk '{print $3}' <<< "$QQ") == "$CurrentQQ_Parent" ]] && continue
        [[ $CurrentQQ_GrandParent ]] && [[ $(awk '{print $3}' <<< "$QQ") == "$CurrentQQ_GrandParent" ]] && continue
        [[ $CurrentQQ_SharedGrandParent ]] && [[ $(awk '{print $3}' <<< "$QQ") == "$CurrentQQ_SharedGrandParent" ]] && continue
        # check for empty transitional processes that are now closed
        QQtempChkPID="$(awk '{print $2}' <<< "$QQ")"
        QQtempChkResult="$(ps -f  --no-header "$QQtempChkPID" 2>/dev/null)"
        [[ ! $QQtempChkResult ]] && QQtempChkResult="null" && continue
        [[ $ShowProcesses ]] && printf "\n QQtempChk for %s is '%s' \n" "$QQtempChkPID" "$QQtempChkResult"
        # remove obscure non-qqX specific
        #[[ "$QQ" == *'/usr/'* ]] && [[ "$QQ" != *'/usr/share/qqX'* ]] && [[ "$QQ" != *'/usr/bin/qqX'* ]] && continue
        [[ "$QQ" == *'qqX_copy_over'* ]] && continue
        # remove qqX_filemanage_qcow, and keep tally for indicative dev output
        if [[ "$QQ" == *'--qqf'* ]] || [[ "$QQ" == *'qqX_filemanage_qcow'* ]]; then
          OtherQQ_qqF_Arr+=("$(awk '{print $2}' <<< "$QQ")")
        else
          # this should now be the count of other instances
          # note, if qqf has been started as a child to a qqX main window, the qqf window will show as a second instance
          # but the count will not include any 'qqX --qqf' separate command line starts
          [[ $QF_exit_to_Main ]] && QF_exit_to_Main=
          OtherQQ_MainArr+=("$(awk '{print $2}' <<< "$QQ")")
        fi
      done
      if [[ $ShowProcesses ]]; then
        [[ $CurrentQQ ]] && printf "\n\n CurrentQQ = %s" "$CurrentQQ"
        [[ $CurrentQQ_Parent ]] && printf "    CurrentQQ_Parent = %s" "$CurrentQQ_Parent"
        [[ $CurrentQQ_GrandParent ]] && printf "    CurrentQQ_GrandParent = %s" "$CurrentQQ_GrandParent"
        [[ $CurrentQQ_SharedGrandParent ]] && printf "    CurrentQQ_SharedGrandParent = %s" "$CurrentQQ_SharedGrandParent"
        printf "\n\n\n RAW Array List  >\n\n"
        declare -p AnotherQQ_Arr
        printf "\n\n Distilled Array (Trigger) List  >   "
        declare -p OtherQQ_MainArr
        printf "\n\n QF Array List  >   "
        declare -p OtherQQ_qqF_Arr; echo
        echo; echo " CurrentQQ_mode= $CurrentQQ_mode"; echo
        read -rp " >  "
      fi
    fi

    if [[ $CurrentQQ_mode == "main" ]] && [[ "${#OtherQQ_MainArr[@]}" -ge 1 ]]; then

      [[ $ShowProcesses ]] && printf "\n\n MULTI_INSTANCE_CHECKS > Messaging and Options > Current Process PID: %s\n\n" "$CurrentQQ"

      qqX_logo_printf_title  "CAUTION: more than one instance of qqX appears to be running: "
      printf "\n\n"
      for Other in "${OtherQQ_MainArr[@]}"; do
        OtherTxt="$(ps --no-header -fo pid,cmd "$Other")"
        OtherTxt="${OtherTxt/'/tmp'/}"
        printf "\n  %s \n" "$OtherTxt"
      done
      printf "\n\n  If running VMs, QEMU will lock protect key files and will prevent things being run simultaneously"
      printf "\n\n  but be aware that minor cross-linking problems can occur, even if simple multi-instance usage is still possible"
      printf "\n\n\n  If qqX upgrading or installing, it may be best to close > some desktop environments can keep an excess numbers of windows open"
      printf "\n\n  OR, this may just be a false alarm ..."
      printf "\n\n\n  [enter] to continue with all   [r] re-check   [k] kill other instances and continue with just this one "
      printColor "\n\n  [q] to quit \n\n"
      read -rp "  >  "   MultiQuit

      [[ $MultiQuit == "q" ]] && exit directly

      if [[ $MultiQuit == "k" ]]; then
        if [[ $(pgrep kvm 2>/dev/null) ]]; then printColor "\n\n  CAUTION: Check for distros that may be running. Force closing can corrupt VM file systems ...."
        else
          printf "\n\n  Killing desktop started instances will close the terminal windows."
          printf "\n\n  CLI instances will terminate but the windows will remain open ..."
          printColor "\n\n\n  Killing other qqX instances ... "
        fi
        printf "\n\n  [k] yes, kill   [enter] continue with all   [q] to quit \n\n"
        read -rp "  >  "  KillQQ
        if [[ $KillQQ == "k" ]]; then
          for QQ in "${OtherQQ_MainArr[@]}"; do
            KillTarget="$(tr -cd '[:digit:]' <<< "$QQ"  2>/dev/null)"
            [[ $ShowProcesses ]] && printf "\n QQ = %  > killing: %s" "$QQ" "$KillTarget"
            [[ $KillTarget ]] &&  kill "$KillTarget" 2>/dev/null
          done
          printColor "\n\n  Closed  \n\n" ; sleep 0.7
        elif [[ $KillQQ == "q" ]]; then exit directly
        fi
      fi

    fi

    if [[ $ShowProcesses ]]; then
      echo; echo "End of function 'MULTI_INSTANCE_CHECKS' > "
      printf "\n\n\n RAW Array List  >\n\n"
      declare -p AnotherQQ_Arr
      printf "\n\n Distilled Array (Trigger) List  >   "
      declare -p OtherQQ_MainArr
      printf "\n\n QF Array List  >   "
      declare -p OtherQQ_qqF_Arr; echo
      printf "\n\n  CurrentQQ = %s" "$CurrentQQ"
      printf "    CurrentQQ_mode = %s\n\n" "$CurrentQQ_mode"
      read -rp " >  "
    fi

    if [[ $MultiQuit == "r" ]]; then
      MultiQuit= ;  printf "\n\n  Re-Checking ...." ; sleep 0.8 ; tput clear ; sleep 0.3
    else break
    fi

  done

  if [[ "$(pgrep quickgui 2>/dev/null)" ]] ; then

    printColor "\n\n  WARNING: an instance of QUICKGUI appears to be running "
    printf "\n\n  Both this program and qqX do have an amount of cross-link protection, however note that:"
    printf "\n\n  Stopping an instance shown as running in QuickGUI may stop an instance started in qqX. \n\n"
    read -rp "  [q] to quit    [enter] to continue  > "   MultiQuit

    [[ $MultiQuit == "q" ]] && exit directly

  fi

  printf "" > "$ConfClearanceLog"

}
