#!/usr/bin/env bash

##  qqX component to be located in folder 'qqX.main'

##  Copyright (c)  Alex Genovese   https://github.com/qqxproject
#   SMALL CODE SNIPPETS eg the function printColor MAY BE USED
#   PERMISSIVELY in projects as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.
# 	Otherwise:
#   Licence  GPL3   https://www.gnu.org/licenses
##  qqX - quickemu quickget X terminal project

## ShellCheck global disables:
# https://www.shellcheck.net/wiki/SC2242 as it clashes with use of exit traps used to keep mouse click scripts open
# And SC1090,SC1091,SC2024, SC2154 for necessity of dynamic file sourcing

#  shellcheck disable=SC2242,SC1090,SC1091,SC2034,SC2154

# Tries to make sure that all current processes have been statted properly and that conflicts are not there:
# Standard COMMAND LINE QEMU (and Quickemu) likes one VM at a time,
# otherwise libvirt/virsh is needed and things no longer stay relatively simple ...

# 2026 changes to the way Gnome and KDE run have complicated process tracing,
# in particular with Gnome where the replacement gnome-terminal 'ptyxis' is still finding its feet.
# From ptyxis version 50.1 onwards we are seeing the WiP dust as somewhat settled but we are still
# unable to boot with window size presets ...

# Different terminals now use different process controls:
# Ptyxis and Konsole will issue new shared (grand)parents for every window, and gnome now uses an intermediary 'ptyxis-agent'
# whereas mate-terminal and qterminal will route all windows through the same parent ...

# To resolve this 2026 dilemma, the instance checker has now been sharded off into its own script
# and the idea of tagging each window/session start with a time based unique identifier has been introduced

# pgrep doesn't always do what it should, tend to use 'ps -ef | grep' as more reliable and more in depth:
# shellcheck disable=SC2016,SC2009


# Run once:

if grep -qs 'time-v7' <<< "$(uuidgen --help)"; then
  qqX_SessionID="$(uuidgen -7)"
  # v7 is better but not available on slower moving distros like linux mint ...
else  qqX_SessionID="$(uuidgen -t)"
fi
qqX_SessionFile="/tmp/qqX_session_$qqX_SessionID"
printf '#!/bin/bash' > "$qqX_SessionFile"
chmod +x "$qqX_SessionFile"
sleep 0.2

MultiQuit= ; KillQQ= ; AnotherQQ_Session_List= ; CurrentQQ_Terminal= ; qqX_Session_List=
CurrentQQ_FullLine= ; CurrentQQ_LastField= ; CurrentQQ= ; CurrentQQ_Parent= ; CurrentQQ_GrandParent=
CurrentQQ_GrandParent_FullLine= ; CurrentQQ_GreatGrandParent= ; CurrentQQ_GreatGrandParent_FullLine=

# create autostop script that finishes when the main process stops,
# only running scripts are detected, and the tmp files will get dropped soon enough
CurrentQQ="$$"
{ printf "\n\nCurrentQQ=\"%s\"\n\n" "$CurrentQQ"
printf 'while [[ $(ps --no-header -f "$CurrentQQ" 2>/dev/null) ]]; do sleep 1 ; done'
printf "\n\n"
} >> "$qqX_SessionFile" &
wait "$!"
# set background ID process running:
"$qqX_SessionFile" &
sleep 0.2

if [[ $ShowProcesses ]]; then
  printf "\n\n General Script 'multi_instance_checks' - RUN ONCE - Current Session: "
  printf "\n\n qqX_SessionID  %s" "$qqX_SessionID"
  printf "\n\n\n" ; printf '    PRE find pid/ppid > ps -ef | grep -i /qqX >' ; printf " \n\n"
  ps -eo pid,ppid,cmd | grep -i '/qqX'
fi

# determine the Current main process Parent PID's
CurrentQQ_FullLine="$(ps --no-header -fo pid,ppid,cmd "$CurrentQQ")"
if [[ "$CurrentQQ_FullLine" != *'/qqX' ]]; then
  CurrentQQ_Input="$(awk '{print $NF}' <<< "$CurrentQQ_FullLine")"
else CurrentQQ_Input=
fi
CurrentQQ_Parent="$(ps --no-header -fo ppid "$CurrentQQ" | tr -cd '[:digit:]')"
CurrentQQ_Parent_FullLine="$(ps --no-header -fo pid,ppid,cmd "$CurrentQQ_Parent")"
CurrentQQ_GrandParent="$(ps --no-header -fo ppid "$CurrentQQ_Parent" | tr -cd '[:digit:]')"
CurrentQQ_GrandParent_FullLine="$(ps --no-header -fo user,pid,ppid,cmd "$CurrentQQ_GrandParent" 2>/dev/null)"
CurrentQQ_GreatGrandParent="$(ps --no-header -fo ppid "$CurrentQQ_GrandParent" | tr -cd '[:digit:]')"
# some distros don't like checks on root activity and may throw errors here, so 2>/dev/null
CurrentQQ_GreatGrandParent_FullLine="$(ps --no-header -fo user,pid,ppid,cmd "$CurrentQQ_GreatGrandParent" 2>/dev/null)"

# Determine terminal window PID:
# All scripts are run by bash, so has '/bash' as part of path in the full ps output,
# and any terminal start that needs 'bash -c' as part of the cmd won't have the forward slash, theoretically ...
# BUT as some terminals run everything from one root and others use one root per window,
# we also need to do a match-up process later on too ...

if [[ $CurrentQQ_GreatGrandParent == "1" ]]; then QQCheckList="$CurrentQQ $CurrentQQ_Parent $CurrentQQ_GrandParent"
else QQCheckList="$CurrentQQ $CurrentQQ_Parent $CurrentQQ_GrandParent $CurrentQQ_GreatGrandParent"
fi

for QQ in $QQCheckList ; do
  QQCheck="$(ps --no-header -f "$QQ")"
  if [[ "$QQCheck" != *'/bash'* ]] && [[ "$QQCheck" == *@('/qqx'|'/qqX')* ]]; then
    CurrentQQ_Terminal="$QQ" && break
  fi
done

[[ $CurrentQQ_Terminal ]] && CurrentQQ_Terminal_FullLine="$(ps --no-header -fo pid,ppid,cmd "$CurrentQQ_Terminal")"

if [[ $ShowProcesses ]]; then
  printf "\n"
  printf "    CurrentQQ \$\$ = %s" "$CurrentQQ"
  printf "    CurrentQQ_Parent = %s" "$CurrentQQ_Parent"
  printf "    CurrentQQ_GrandParent = %s" "$CurrentQQ_GrandParent"
  printf "    CurrentQQ_GreatGrandParent = %s" "$CurrentQQ_GreatGrandParent"

  printf "\n\n    CurrentQQ_FullLine = %s" "$CurrentQQ_FullLine"

  if [[ $CurrentQQ_Input ]]; then printf "\n\n    CurrentQQ_Input = %s" "$CurrentQQ_Input"
  else  printf "\n\n    CurrentQQ_Input = no specific targets"
  fi

  printf "\n\n    CurrentQQ_Terminal = %s" "$CurrentQQ_Terminal"
  printf "\n\n    CurrentQQ_Terminal_FullLine = %s" "$CurrentQQ_Terminal_FullLine"
  printf "\n\n    UserTerm = %s" "$UserTerm"
  printf "\n\n    CurrentQQ_Parent_FullLine = %s" "$CurrentQQ_Parent_FullLine"
  printf "\n\n    CurrentQQ_GrandParent_FullLine = '%s'" "$CurrentQQ_GrandParent_FullLine"
  printf "\n\n    CurrentQQ_GreatGrandParent_FullLine = '%s'" "$CurrentQQ_GreatGrandParent_FullLine"
fi

# Re-checkable:

function multi_instance_checks {

  while true; do

    # NOTE use 'ps' here as pgrep can cause problems  (plus ignore any root process history from installer or copy-over)
    # pgrep -an is not reliable and pgrep sub-shell creates another pid too ...
    # shellcheck disable=SC2009

    qqX_Session_List="$(ps -ef | grep -s qqX_session | grep -v grep)"
    [[ $qqX_Session_List ]] && AnotherQQ_Session_List="$(grep -sv "$qqX_SessionID" <<< "$qqX_Session_List")"

    # If loading up the qcow menu, but then not choosing the qf option,
    # then the currrent qcow ceases to be a duplicate, and we need the VM selector interface, not the main selected one
    if [[ $Trace_InputVars ]]; then
      printf "\n\n Chrome up: Positional Vars = %s" "$*"
      printf "\n\n QF_exit_to_Main is %s" "$QF_exit_to_Main"
      printf "\n\n XDG_MimeType_Recognised is %s" "$XDG_MimeType_Recognised"
      printf "\n\n XDG_MimeType_is_ISO is %s" "$XDG_MimeType_is_ISO"
      printf "\n\n XDG_MimeType_is_QCOW is %s" "$XDG_MimeType_is_QCOW"
      printf "\n\n XDG_Input_NON_qqX is %s \n\n" "$XDG_Input_NON_qqX"
      echo " pwd  $(pwd)"
      echo; sleep "$Trace_InputVars"
    fi

    # CL launched running of qcow2 file management happens before this script is called. See qqX start.
    # Running CL instances will show up with 'pgrep -aAxi qqX' as 'pid /bin/bash /usr/bin/qqX --qqf' or similar
    # With pgrep -afi qqX_filemanage as: pid /bin/bash /usr/share/qqX/qqX.main/qqX_filemanage_qcow_drive --qqf

    if [[ $ShowProcesses ]]; then
      printf "\n\n\n Function 'MULTI_INSTANCE_CHECKS' Session Checker "
      printf "\n\n\n qqX_Session_List:"; [[ $qqX_Session_List ]] && printf "\n%s" "$qqX_Session_List"
      printf "\n\n AnotherQQ_Session_List:"; [[ $AnotherQQ_Session_List ]] && printf "\n%s" "$AnotherQQ_Session_List"
      printf "\n\n\n QF_exit_to_Main = %s \n\n" "$QF_exit_to_Main"
    fi

    SharedTerminalRoot=
    AnotherQQ_SessionArr=()
    AnotherQQ_MainArr=()

    if [[ $AnotherQQ_Session_List ]]; then

      mapfile -t AnotherQQ_SessionArr <<< "$AnotherQQ_Session_List"

      for QQ in "${AnotherQQ_SessionArr[@]}"; do

        # Find the session parent PID, which will be the main process, but not necessarily the window root
        # The KillPointPID gets recorded in the AnotherQQ_MainArr and will depend on which terminal is being used

        local SessionQQ="" SessionQQ_Parent="" SessionQQ_Parent_FullLine="" SessionQQ_GrandParent="" SessionQQ_GrandParent_FullLine=""
        local SessionQQ_GreatGrandParent="" SessionQQ_GreatGrandParent_FullLine=""
        SessionQQ="$(awk '{print $2}' <<< "$QQ")"
        SessionQQ_Parent="$(awk '{print $3}' <<< "$QQ")"
        SessionQQ_Parent_FullLine="$(ps --no-header -fo pid,ppid,cmd "$SessionQQ_Parent")"
        SessionQQ_GrandParent="$(ps --no-header -fo ppid "$SessionQQ_Parent" | tr -cd '[:digit:]')"
        SessionQQ_GrandParent_FullLine="$(ps --no-header -fo user,pid,ppid,cmd "$SessionQQ_GrandParent")"
        SessionQQ_GreatGrandParent="$(ps --no-header -fo ppid "$SessionQQ_GrandParent" | tr -cd '[:digit:]')"
        SessionQQ_GreatGrandParent_FullLine="$(ps --no-header -fo user,pid,ppid,cmd "$SessionQQ_GreatGrandParent")"

        if [[ "$SessionQQ_Parent_FullLine" != *'/bash'* ]] && [[ "$SessionQQ_Parent_FullLine" == *@('/qqx'|'/qqX')* ]]; then
          # don't risk killing system processes (check qqX is present ...)
          if [[ $SessionQQ_Parent == "$CurrentQQ_Terminal" ]]; then
            SharedTerminalRoot="$CurrentQQ_Terminal" ; AnotherQQ_MainArr+=("$SessionQQ")
          else AnotherQQ_MainArr+=("$SessionQQ_Parent")
          fi
          [[ $ShowProcesses ]] && printf "\n\n  parent test %s %s" "$SessionQQ_Parent" "$CurrentQQ_Terminal"
        elif [[ "$SessionQQ_GrandParent_FullLine" != *'/bash'* ]] && [[ "$SessionQQ_GrandParent_FullLine" == *@('/qqx'|'/qqX')* ]]; then
          if [[ $SessionQQ_GrandParent == "$CurrentQQ_Terminal" ]]; then
            SharedTerminalRoot="$CurrentQQ_Terminal" ; AnotherQQ_MainArr+=("$SessionQQ_Parent")
          else AnotherQQ_MainArr+=("$SessionQQ_GrandParent")
          fi
          [[ $ShowProcesses ]] && printf "\n\n  grand parent test %s %s" "$SessionQQ_GrandParent" "$CurrentQQ_Terminal"
        elif [[ "$SessionQQ_GreatGrandParent_FullLine" != *'/bash'* ]] && [[ "$SessionQQ_GreatGrandParent_FullLine" == *@('/qqx'|'/qqX')* ]]; then
          if [[ $SessionQQ_GreatGrandParent == "$CurrentQQ_Terminal" ]];then
            SharedTerminalRoot="$CurrentQQ_Terminal" ; AnotherQQ_MainArr+=("$SessionQQ_GrandParent")
          else AnotherQQ_MainArr+=("$SessionQQ_GreatGrandParent")
          fi
          [[ $ShowProcesses ]] && printf "\n\n  great grand parent test %s %s" "$SessionQQ_GreatGrandParent" "$CurrentQQ_Terminal"
        else
          # make the best of a bad job (should stop processes but may leave windows open)
          AnotherQQ_MainArr+=("$SessionQQ_Parent")
        fi

        if [[ $ShowProcesses ]]; then
          printf "\n\n    QQ loop item = %s" "$QQ"
          printf "\n\n    SessionQQ = %s" "$SessionQQ"
          printf "    SessionQQ_Parent = %s" "$SessionQQ_Parent"
          printf "    SessionQQ_GrandParent = %s" "$SessionQQ_GrandParent"
          printf "    SessionQQ_GreatGrandParent = %s" "$SessionQQ_GreatGrandParent"
          printf "\n\n    SessionQQ_Parent = %s" "$SessionQQ_Parent_FullLine"
          printf "\n\n    SessionQQ_GrandParent = %s" "$SessionQQ_GrandParent_FullLine"
          printf "\n\n    SessionQQ_GreatGrandParent = %s" "$SessionQQ_GreatGrandParent_FullLine"
          [[ $SharedTerminalRoot ]] && printf "\n\n\n    SharedTerminalRoot = %s \n\n" "$CurrentQQ_Terminal_FullLine"
        fi

      done

      if [[ $ShowProcesses ]]; then
        printf "\n\n\n OTHER Session PID Array:"
        if [[ ${AnotherQQ_SessionArr[0]} ]]; then printf "\n\n" ; declare -p AnotherQQ_SessionArr
        else printf "  NONE"
        fi
        printf "\n\n OTHER Terminal PID Array:"
        if [[ ${AnotherQQ_MainArr[0]} ]]; then printf "\n\n" ; declare -p AnotherQQ_MainArr
        else printf "  NONE"
        fi
        printf "\n\n"
        read -rp " >  "
      fi

    fi

    if [[ "${#AnotherQQ_MainArr[@]}" -ge 1 ]]; then

      [[ $ShowProcesses ]] && printf "\n\n MULTI_INSTANCE_CHECKS > Messaging and Options > Current Process PID: %s\n\n" "$CurrentQQ"

      qqX_logo_printf_title  "CAUTION: more than one instance of qqX appears to be running "
      printf "\n\n"
      printf "\n\n  Current Session  %s  is:" "$qqX_SessionID"
      printf "\n\n   %s" "$(ps --no-header -fo pid,cmd "$CurrentQQ_Terminal")"
      printf "\n\n  Other Sessions: \n"
      for Other in "${AnotherQQ_MainArr[@]}"; do
        OtherTxt="$(ps --no-header -fo pid,cmd "$Other")"
        OtherTxt="${OtherTxt/'/tmp'/}"
        printf "\n  %s \n" "$OtherTxt"
      done
      printf "\n\n  If running VMs, QEMU will lock protect key files and will prevent things being run simultaneously"
      printf "\n\n  but be aware that minor cross-linking problems can occur, even if simple multi-instance usage is still possible,"
      printf "\n\n  and that killing other instances could force-close or CRASH other VMs or processes"
      printf "\n\n\n  If qqX upgrading or installing, it may be best to close > some desktop environments can keep an excess numbers of windows open"
      printf "\n\n  OR, this may just be a false alarm ..."
      printf "\n\n\n  [enter] to continue with all   [r] re-check   [k] kill other instances and continue with just this one "
      printColor "\n\n  [q] to quit \n\n"
      read -rp "  >  "   MultiQuit

      [[ $MultiQuit == "q" ]] && exit directly

      if [[ $MultiQuit == "k" ]]; then
        if [[ $(pgrep kvm 2>/dev/null) ]]; then printColor "\n\n  CAUTION: Check for distros that may be running. Force closing can corrupt VM file systems ...."
        else
          printf "\n\n  Killing desktop started instances will close the terminal windows."
          printf "\n\n  CLI instances will terminate but the windows will remain open ..."
          printColor "\n\n\n  Killing other qqX instances ... "
        fi
        printf "\n\n  [k] yes, kill   [enter] continue with all   [q] to quit \n\n"
        read -rp "  >  "  KillQQ
        if [[ $KillQQ == "k" ]]; then
          for QQ in "${AnotherQQ_MainArr[@]}"; do
            KillTarget="$(tr -cd '[:digit:]' <<< "$QQ"  2>/dev/null)"
            [[ $ShowProcesses ]] && printf "\n QQ = %s  > killing: %s" "$QQ" "$KillTarget"
            [[ $KillTarget ]] &&  kill -15 "$KillTarget" 2>/dev/null
          done
          printColor "\n\n  Closed  \n\n" ; sleep 0.7
        elif [[ $KillQQ == "q" ]]; then exit directly
        fi
      fi

    fi

    if [[ $ShowProcesses ]] && [[ $MultiQuit != "r" ]]; then
      printf "\n\n Function 'MULTI_INSTANCE_CHECKS' "
      printf "\n\n\n OTHER Session PID Array:"
      if [[ ${AnotherQQ_SessionArr[0]} ]]; then printf "\n\n" ; declare -p AnotherQQ_SessionArr
      else printf "  NONE"
      fi
      printf "\n\n OTHER Terminal PID Array:"
      if [[ ${AnotherQQ_MainArr[0]} ]]; then printf "\n\n" ; declare -p AnotherQQ_MainArr
      else printf "  NONE"
      fi
      printf "\n\n"
      read -rp " >  "
    fi

    if [[ $MultiQuit == "r" ]]; then
      MultiQuit= ;  printf "\n\n  Re-Checking .... \n\n" ; sleep 1.5 ; tput clear ; sleep 0.3
    else break
    fi

  done

  if [[ "$(pgrep quickgui 2>/dev/null)" ]] ; then

    printColor "\n\n  WARNING: an instance of QUICKGUI appears to be running "
    printf "\n\n  Both this program and qqX do have an amount of cross-link protection, however note that:"
    printf "\n\n  Stopping an instance shown as running in QuickGUI may stop an instance started in qqX. \n\n"
    read -rp "  [q] to quit    [enter] to continue  > "   MultiQuit

    [[ $MultiQuit == "q" ]] && exit directly

  fi

  printf "" > "$ConfClearanceLog"

}
