#!/usr/bin/env bash

##  qqX component to be located in folder 'qqX.main'

##  Copyright (c)  Alex Genovese   https://github.com/qqxproject
#   SMALL CODE SNIPPETS eg the function printColor MAY BE USED
#   PERMISSIVELY in projects as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.
# 	Otherwise:
#   Licence  GPL3   https://www.gnu.org/licenses
##  qqX - quickemu quickget X terminal project

## ShellCheck global disables:
# https://www.shellcheck.net/wiki/SC2242 as it clashes with use of exit traps used to keep mouse click scripts open
# And SC1090,SC1091,SC2024, SC2154 for necessity of dynamic file sourcing

#  shellcheck disable=SC2242,SC1090,SC1091,SC2034,SC2154

#  GENERAL COLOR & THEMING   (see settings)

[[ ! $X_Shade ]] &&  X_Shade="3"

#  Yellow 3 (recommended), Blue 4, Cyan 6 (brighter blue), Red 1
#  https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit
#  https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x405.html
#  if source without declared shade, set default shade


# non-color ECHO TRAP, mainly designed to capture the technical output that quickemu doesn't send to log file
printf "\n"  > "/tmp/qqX_echo_output.log"

echo () {

  if [[ $UseCustomBootArgs ]]; then
    command echo "$@" >>  "/tmp/qqX_echo_output.log" ;
  else
    command echo "$@" | tee -a  "/tmp/qqX_echo_output.log" ;
  fi

}

printColor () {
	tput setaf "$X_Shade"
	# shellcheck disable=SC2059
	printf "$@"
	tput sgr0
}

# avoid use of echo near the vm boot section, to avoid clashes with the log file

echColor () {
	if [[ $2 ]] ; then
		if [[ "$1" == "-n" ]] ; then
			tput setaf "$X_Shade"
			echo -n "$2"
			tput sgr0
		else
			tput setaf "$X_Shade"
			echo "$@"
			tput sgr0
		fi
	else
		tput setaf "$X_Shade"
		echo "$1"
		tput sgr0
	fi
}


# General default title:
qqX_title="[quickemu quickget X terminal project] - $qqX_Version - simply better ..."

## qqX chrome up

qqX_logo() {
  # not for use during vm boot sequences
  echColor "  _    _   \/   "
  echColor " (_|  (_|  /\ "
  echColor "   |.   |.    "
}

qqX_logo_plain() {
  # early loader
  echo "  _    _   \/   "
  echo " (_|  (_|  /\ "
  echo "   |.   |.    "
}

qqX_logo_printf() {
  # printf version (no end line feed)
  printColor "  _    _   \/   "
  printColor " (_|  (_|  /\ "
  printColor "   |.   |.    "
}

# Variant on   http://www.figlet.org/  -f mini  (-k)   (c)  Alex Genovese

qqX_logo_title() {
  # not for use during vm boot sequences
  if [[ $1 ]]; then qqX_LogoTxt="$1" ; else qqX_LogoTxt="$qqX_title" ; fi
  echColor "  _    _   \/   "
  echColor " (_|  (_|  /\ "
  echColor "   |.   |.     $qqX_LogoTxt"
}

qqX_logo_printf_title() {
  # printf version (no end line feed & also avoids the quickemu echo trap)
  if [[ $1 ]]; then qqX_LogoTxt="$1" ; else qqX_LogoTxt="$qqX_title" ; fi
  printColor "\n  _    _   \/   "
  printColor "\n (_|  (_|  /\ "
  printColor "\n   |.   |.     %s"  "$qqX_LogoTxt"
}


function exit {

  # trap to keep terminal open if started by mouse click  -t secs
  # or to stop sourced quickemu quitting as 'normal' procedure   (tput resets any hidden cursors)
  # https://unix.stackexchange.com/questions/220330/hide-and-unhide-cursor-with-tput

  if [[ $1 == "directly" ]]; then
    printf "\n  Stopping current qqX process .... \n\n"
    sleep 1.4 ; tput cnorm ; tput clear
    [[ $DolphinExitPid ]] && kill "$DolphinExitPid"
    command exit

  elif [[ $1 ]] && [[ ! $NoExit ]]; then
    ExitTrap=
    printf "\n\n"
    printColor "  ERROR :    [c] ignore and continue  [m] attempt return to menus  [q] quit  \n\n"
    read -rp  "  >  "  ExitTrap
    if [[ $ExitTrap != "m" ]]; then
      ExitTrap=
      printf "\n\n  CONFIRM >  [c] ignore and continue  [m] attempt return to menus  [q] quit  \n\n"
      read -rp "  >  "  ExitTrap
      printf "\n\n"
    fi
    if [[ $ExitTrap == "q" ]]; then
      printf "  Stopping current qqX process .... \n\n"
      sleep 1.4 ; tput cnorm ; tput clear
      [[ $DolphinExitPid ]] && kill "$DolphinExitPid"
      command exit "$@"
    # 'm' attempts a return, given an error situation exists
    elif [[ $ExitTrap == "c" ]]; then true
    else RouteToMenus=1
    fi
    ExitTrap=
    return

  elif [[ ! $disk_img ]]; then
    # don't exit on quickemu error no disk defined, this is handled by qqX  REVIEW
    return

  fi

  # zero the optional 'exit 1' bypass flag (if it has been set)
  NoExit=
}

# Tests for these programs will have been made just previously in the read_main_settings script
# but placing the message functions here allows these functions to run elsewhere
# See function qcow2_filemanagement_launcher

texteditor_not_found_message () {
  printColor "\n\n  Unable to open settings or show some help sections without an editor."
  printf "\n\n  Default or basic text editors will be tried or have been tried ..."
  printf "\n\n  Give settings file the command name of a preferred editor."
  printf "\n\n  Settings location:  %s  \n\n  [enter] to return \n\n"  "$qqX_SettingsFile"
  read -rp "  >  "
}

web_browser_not_found_message () {
  printColor "\n\n  Add Web Browser to GENERAL SETTINGS:"
  printf "\n\n  None of the usual or default Web Browsers can be found ..."
  printf "\n\n  Give settings file the command name of a preferred browser."
  printf "\n\n  Settings location:  %s  \n\n  [enter] to return \n\n"  "$qqX_SettingsFile"
  read -rp "  >  "
}

file_manager_not_found_message () {
  printColor "\n\n  Add File Manager to GENERAL SETTINGS:"
  printf "\n\n  None of the usual or default File Managers can be found ..."
  printf "\n\n  Give settings file the command name of a preferred manager."
  printf "\n\n  Settings location:  %s  \n\n  [enter] to return \n\n"  "$qqX_SettingsFile"
  read -rp "  >  "
}

show_qqX_title_bar() {

  if [[ ! $LatestQEMU ]] && grep -qsE ^'[0-9]' "/tmp/latest-qemu.txt"; then  LatestQEMU="$(cat "/tmp/latest-qemu.txt")"; fi

  qqX_logo_printf_title  "$qqX_title" ;  printf "\n"
  printf "\n\n  Currently wrapping:  QEMU %s" "$QEMU_VER_LONG"
  if [[ $LatestQEMU ]]; then
    if [[ $QEMU_VER_LONG == "$LatestQEMU" ]]; then  printf "  (latest)   "
    else printf "  (latest: %s)   " "$LatestQEMU"
    fi
  else printf "   "
  fi
  printf "quickemu %s (mods %s) &  quickget %s (mods %s) '%s'"  "$QE_VerNumber" "$QE_ModsNumber" "$QG_VerNumber" "$QG_ModsNumber" "$QE_SourceVersion"

  if [[ $DevStart ]]; then
    printf "\n\n  Using Code: %s " "$QE_SourcePath"
    [[ $CodingHotSwap ]] && CodingHotSwapShow=
  fi

  PWD_Folder="$(pwd)"
  HideFolderTitleBar=

  for TF in "${Extra_VM_Folder[@]}"; do
    [[ $TF ==  "$PWD_Folder" ]] || [[ $PWD_Folder ==  "$Default_VM_Folder" ]] &&  HideFolderTitleBar=1
  done

  if [[ ! $Current_VM_Folder ]]; then
    Current_VM_Folder="$Default_VM_Folder"
    cd "$Default_VM_Folder" || printf "\n\n  ChromeUp ERROR sorting Current Folder"
  fi

  if [[ ! $HideFolderTitleBar ]]; then
    printf "\n\n  Default Folder: %s   Current Folder: %s \n"  "$Default_VM_Folder" "$Current_VM_Folder"
  else
    printf "\n"
  fi

  [[ $Loop_Diagnostics ]] && printf "\n\n Post show_qqX_title_bar :" &&  main_loop_diagnostics  && printf "\n\n"

}

function show_qqX_general_help {

  HelpSelect=
  while true; do

    if [[ $1 ]]; then  HelpSelect="$1" ; shift
    fi
    tput clear
    printColor "\n\n  GENERAL HELP:"
    cat "$HOME/.qqX/icons/qqX.ascii.logo.8bit.25.txt"
    printf "\n  [s] open general settings file for notes on the  SETTINGS, user modes, screen sizes etc"
    printf  "\n\n  [f] see FreeBird notes  [c] command line & mouse notes"

    if [[ $WebBrowser ]]; then
      printf "\n\n\n  [w] Online HELP PAGES, FAQs and Release Notes @ qqxproject.org   [dw] DeepWiki on how qqX works under the hood"
      printColor "\n\n  [N] latest news and discussion @ qqX GitHub"
      if [[ $guest_os == "windows" ]]; then
        WinVirtDate="$(curl -qsLf -m 3 "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/" | grep 'latest-virtio' | tr '>' '\n' | grep 20 | awk '{print $1}')"
        printf "\n\n  Latest Windows Guest drivers:  %s  https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio" "$WinVirtDate"
      fi
      printf "\n\n\n"
      if [[ $ShowTxTexts ]]; then printColor  "  [tx] %s" "$MainTxOptionLine"
      else printf  "  [tx] %s" "$MainTxOptionLine"
      fi
    else
      printColor "\n\n  Check settings: Web Browser not found ??  https://qqxproject.org/FAQs-and-Help"
    fi
    printf  "\n\n  [enter] to return"
    printf "\n\n"
    [[ $HelpSelect ]] || read -rp "  >  "  HelpSelect

    if [[ $HelpSelect == "c" ]]; then
      show_CLI_usage
      printf  "\n  [enter] to return"
      printf "\n\n"
      read -rp  "   >  " HelpSelect

    elif [[ $HelpSelect == "f" ]]; then
      printf "\n  Hot-Swappable from all main menus:  [FS] FreeSpirit  [FB] FreeBird  [HB]  [Cust]  [Dev] \n\n"
      grep -m 1 -A 100  'named as follows' "$qqX_SettingsFile" | grep -m 1 -B 100 '# FreeBird or FreeSpirit are recommended'| tr '#' ' '

      printf "\n  HotSwaps should be problem free and full reboot not required."

      if [[ -e "$Default_VM_Folder/qqX.custom/QE.Custom/quickemu" ]]; then
        printf "\n\n  Custom =   Default_VM_Folder > qqX.custom  > %s " "$("$Default_VM_Folder/qqX.custom/QE.Custom/quickemu" --version)"
      fi
      if [[ -e "$QE_DevPath/quickemu" ]]; then
        printf "\n\n  Dev =   %s  > %s " "$QE_DevPath"  "$("$QE_DevPath/quickemu" --version)"
      fi

      printf "\n\n  [enter] to return \n\n"
      read -rp  "  >  " HelpSelect

    elif [[ $HelpSelect == "tx" ]]; then
      HelpSelect= ; main_translation_menu

    elif [[ $HelpSelect == "w" ]]; then
      HelpSelect=
      printf "\n  Opening Browser ... \n"
      (nohup &> /dev/null  "$WebBrowser" "https://qqxproject.org/FAQs-and-Help"  & ) || web_browser_not_found_message
      sleep 1

    elif [[ $HelpSelect == "dw" ]]; then
      HelpSelect=
      printf "\n  Opening Browser ... \n"
      (nohup &> /dev/null  "$WebBrowser" "https://deepwiki.com/qqxproject/qqX"  & ) || web_browser_not_found_message
      sleep 1

    elif [[ $HelpSelect == "n" ]] || [[ $HelpSelect == "N" ]]; then
      HelpSelect=
      printf "\n  Opening Browser ... \n"
      (nohup &> /dev/null  "$WebBrowser" "https://github.com/qqxproject/qqX/discussions/categories/announcements"  & ) || web_browser_not_found_message
      sleep 1

    elif [[ $HelpSelect == "s" ]]; then
      HelpSelect=
      qqX_edit_settings

    else
      HelpSelect=
      break
    fi

  done

}

