#!/usr/bin/env bash

##  qqX component to be located in folder 'qqX.main'

##  Copyright (c)  Alex Genovese   https://github.com/qqxproject
#   SMALL CODE SNIPPETS eg the function printColor MAY BE USED
#   PERMISSIVELY in projects as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.
# 	Otherwise:
#   Licence  GPL3   https://www.gnu.org/licenses
##  qqX - quickemu quickget X terminal project

## ShellCheck global disables:
# https://www.shellcheck.net/wiki/SC2242 as it clashes with use of exit traps used to keep mouse click scripts open
# And SC1090,SC1091,SC2024, SC2154 for necessity of dynamic file sourcing

#  shellcheck disable=SC2242,SC1090,SC1091,SC2034,SC2154

#  GENERAL COLOR & THEMING   (see settings)

[[ ! $X_Shade ]] &&  X_Shade="3"

#  Yellow 3 (recommended), Blue 4, Cyan 6 (brighter blue), Red 1
#  https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit
#  https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x405.html
#  if source without declared shade, set default shade


# non-color ECHO TRAP, mainly designed to capture the technical output that quickemu doesn't send to log file
printf "\n"  > "/tmp/qqX_echo_output.log"

echo () {

  if [[ $UseCustomBootArgs ]]; then
    command echo "$@" >>  "/tmp/qqX_echo_output.log" ;
  else
    command echo "$@" | tee -a  "/tmp/qqX_echo_output.log" ;
  fi

}

printColor () {
	tput setaf "$X_Shade"
	# shellcheck disable=SC2059
	printf "$@"
	tput sgr0
}

# avoid use of echo near the vm boot section, to avoid clashes with the log file

echColor () {
	if [[ $2 ]] ; then
		if [[ "$1" == "-n" ]] ; then
			tput setaf "$X_Shade"
			echo -n "$2"
			tput sgr0
		else
			tput setaf "$X_Shade"
			echo "$@"
			tput sgr0
		fi
	else
		tput setaf "$X_Shade"
		echo "$1"
		tput sgr0
	fi
}


# General default title:
qqX_title="[quickemu quickget X terminal project] - $qqX_Version - simply better ..."

## qqX chrome up

qqX_logo() {
  # not for use during vm boot sequences
  echColor "  _    _   \/   "
  echColor " (_|  (_|  /\ "
  echColor "   |.   |.    "
}

qqX_logo_plain() {
  # early loader
  echo "  _    _   \/   "
  echo " (_|  (_|  /\ "
  echo "   |.   |.    "
}

qqX_logo_printf() {
  # printf version (no end line feed)
  printColor "  _    _   \/   "
  printColor " (_|  (_|  /\ "
  printColor "   |.   |.    "
}

# Variant on   http://www.figlet.org/  -f mini  (-k)   (c)  Alex Genovese

qqX_logo_title() {
  # not for use during vm boot sequences
  if [[ $1 ]]; then qqX_LogoTxt="$1" ; else qqX_LogoTxt="$qqX_title" ; fi
  echColor "  _    _   \/   "
  echColor " (_|  (_|  /\ "
  echColor "   |.   |.     $qqX_LogoTxt"
}

qqX_logo_printf_title() {
  # printf version (no end line feed & also avoids the quickemu echo trap)
  if [[ $1 ]]; then qqX_LogoTxt="$1" ; else qqX_LogoTxt="$qqX_title" ; fi
  printColor "\n  _    _   \/   "
  printColor "\n (_|  (_|  /\ "
  printColor "\n   |.   |.     %s"  "$qqX_LogoTxt"
}


function exit {

  # trap to keep terminal open if started by mouse click  -t secs
  # or to stop sourced quickemu quitting as 'normal' procedure   (tput resets any hidden cursors)
  # https://unix.stackexchange.com/questions/220330/hide-and-unhide-cursor-with-tput

  if [[ $1 == "directly" ]]; then
    tput cnorm
    command exit

  elif [[ $1 ]] && [[ ! $NoExit ]]; then
    ExitTrap=
    printf "\n\n"
    printColor "  ERROR :    [c] ignore and continue  [m] attempt return to menus  [q] quit  \n\n"
    read -rp  "  >  "  ExitTrap
    if [[ $ExitTrap != "m" ]]; then
      ExitTrap=
      printf "\n\n  CONFIRM >  [c] ignore and continue  [m] attempt return to menus  [q] quit  \n\n"
      read -rp "  >  "  ExitTrap
    fi
    if [[ $ExitTrap == "q" ]]; then
      tput cnorm
      command exit "$@"
    # 'm' attempts a return, given an error situation exists
    elif [[ $ExitTrap == "c" ]]; then true
    else RouteToMenus=1
    fi
    ExitTrap=
    return

  elif [[ ! $disk_img ]]; then
    # don't exit on quickemu error no disk defined, this is handled by qqX  REVIEW
    return

  fi

  # zero the optional 'exit 1' bypass flag (if it has been set)
  NoExit=
}

# Tests for these programs will have been made just previously in the read_main_settings script
# but placing the message functions here allows these functions to run elsewhere
# See function qcow2_filemanagement_launcher

texteditor_not_found_message () {
  printColor "\n\n  Unable to open settings or show some help sections without an editor."
  printf "\n\n  Default or basic text editors will be tried or have been tried ..."
  printf "\n\n  Give settings file the command name of a preferred editor."
  printf "\n\n  Settings location:  %s  \n\n  [enter] to return \n\n"  "$qqX_SettingsFile"
  read -rp "  >  "
}

web_browser_not_found_message () {
  printColor "\n\n  Add Web Browser to GENERAL SETTINGS:"
  printf "\n\n  None of the usual or default Web Browsers can be found ..."
  printf "\n\n  Give settings file the command name of a preferred browser."
  printf "\n\n  Settings location:  %s  \n\n  [enter] to return \n\n"  "$qqX_SettingsFile"
  read -rp "  >  "
}

file_manager_not_found_message () {
  printColor "\n\n  Add File Manager to GENERAL SETTINGS:"
  printf "\n\n  None of the usual or default File Managers can be found ..."
  printf "\n\n  Give settings file the command name of a preferred manager."
  printf "\n\n  Settings location:  %s  \n\n  [enter] to return \n\n"  "$qqX_SettingsFile"
  read -rp "  >  "
}

show_qqX_title_bar() {

  if [[ ! $LatestQEMU ]] && grep -qsE ^'[0-9]' "/tmp/latest-qemu.txt"; then  LatestQEMU="$(cat "/tmp/latest-qemu.txt")"; fi

  qqX_logo_printf_title  "$qqX_title" ;  printf "\n"
  printf "\n\n  Currently wrapping:  QEMU %s" "$QEMU_VER_LONG"
  if [[ $LatestQEMU ]]; then
    if [[ $QEMU_VER_LONG == "$LatestQEMU" ]]; then  printf "  (latest)   "
    else printf "  (latest: %s)   " "$LatestQEMU"
    fi
  else printf "   "
  fi
  printf "quickemu %s (mods %s) &  quickget %s (mods %s) '%s'"  "$QE_VerNumber" "$QE_ModsNumber" "$QG_VerNumber" "$QG_ModsNumber" "$QE_SourceVersion"

  if [[ $DevStart ]]; then
    printf "\n\n  Using Code: %s " "$QE_SourcePath"
    [[ $CodingHotSwap ]] && CodingHotSwapShow=
  fi

  PWD_Folder="$(pwd)"
  HideFolderTitleBar=

  for TF in "${Extra_VM_Folder[@]}"; do
    [[ $TF ==  "$PWD_Folder" ]] || [[ $PWD_Folder ==  "$Default_VM_Folder" ]] &&  HideFolderTitleBar=1
  done

  if [[ ! $Current_VM_Folder ]]; then
    Current_VM_Folder="$Default_VM_Folder"
    cd "$Default_VM_Folder" || printf "\n\n  ChromeUp ERROR sorting Current Folder"
  fi

  if [[ ! $HideFolderTitleBar ]]; then
    printf "\n\n  Default Folder: %s   Current Folder: %s \n"  "$Default_VM_Folder" "$Current_VM_Folder"
  else
    printf "\n"
  fi

  [[ $Loop_Diagnostics ]] && printf "\n\n Post show_qqX_title_bar :" &&  main_loop_diagnostics  && printf "\n\n"

}

function show_qqX_general_help {

  HelpSelect=
  while true; do

    if [[ $1 ]]; then  HelpSelect="$1" ; shift
    fi
    tput clear
    printColor "\n\n  GENERAL HELP:"
    cat "$HOME/.qqX/icons/qqX.ascii.logo.8bit.25.txt"
    printf "\n  [s] open general settings file for notes on the  SETTINGS, user modes, screen sizes etc"
    printf  "\n\n  [f] see FreeBird notes  [c] command line & mouse notes"
    if [[ $WebBrowser ]]; then
      printColor "\n\n  [w] Online: HELP PAGES, FAQs and Release Notes @ https://qqxproject.org"
      printf "\n\n"
      if [[ $ShowTxTexts ]]; then printColor  "  [tx] %s" "$MainTxOptionLine"
      else printf  "  [tx] %s" "$MainTxOptionLine"
      fi
    else
      printColor "\n\n  Check settings: Web Browser not found ??  https://qqxproject.org/FAQs-and-Help"
    fi
    printf  "\n\n  [enter] to return"
    printf "\n\n"
    [[ $HelpSelect ]] || read -rp "  >  "  HelpSelect

    if [[ $HelpSelect == "c" ]]; then
      show_CLI_usage
      printf  "\n  [enter] to return"
      printf "\n\n"
      read -rp  "   >  " HelpSelect

    elif [[ $HelpSelect == "f" ]]; then
      printf "\n  Hot-Swappable from all main menus:  [FS] FreeSpirit  [FB] FreeBird  [HB]  [Cust]  [Dev] \n\n"
      grep -m 1 -A 100  'named as follows' "$qqX_SettingsFile" | grep -m 1 -B 100 '# FreeBird or FreeSpirit are recommended'| tr '#' ' '

      printf "\n  HotSwaps should be problem free and full reboot not required."

      if [[ -e "$Default_VM_Folder/qqX.custom/QE.Custom/quickemu" ]]; then
        printf "\n\n  Custom =   Default_VM_Folder > qqX.custom  > %s " "$("$Default_VM_Folder/qqX.custom/QE.Custom/quickemu" --version)"
      fi
      if [[ -e "$QE_DevPath/quickemu" ]]; then
        printf "\n\n  Dev =   %s  > %s " "$QE_DevPath"  "$("$QE_DevPath/quickemu" --version)"
      fi

      printf "\n\n  [enter] to return \n\n"
      read -rp  "  >  " HelpSelect

    elif [[ $HelpSelect == "tx" ]]; then
      HelpSelect= ; main_translation_menu

    elif [[ $HelpSelect == "w" ]]; then
      HelpSelect=
      printf "\n  Opening Browser ... \n"
      (nohup &> /dev/null  "$WebBrowser"  "https://qqxproject.org/FAQs-and-Help"  & ) || web_browser_not_found_message
      sleep 1

    elif [[ $HelpSelect == "s" ]]; then
      HelpSelect=
      qqX_edit_settings

    else
      HelpSelect=
      break
    fi

  done

}


function multi_instance_checks {

  # Make sure that all current processes have been statted properly before moving on.
  # pgrep -an is not reliable and pgrep sub-shell creates another pid too.
  # BUT new PID always goes on end of list so check for this until no 'kworker' grep errors
  # and without any background updater checks (qqxproject/qqX/tags) or calls to qqX lib (/usr/share)

  # The 'up' bit  of Chrome Up  but REVIEW placing elsewhere ??

  if [[ $ShowProcesses ]]; then
    printf "\n\nScript: qqX_UI_chrome_up > function 'MULTI_INSTANCE_CHECKS' > \n\n"
    printf "\n\n    PRE find pid/ppid > pgrep -afi '/qqX' > \n\n"
    pgrep -afi '/qqX'
  fi

  sleep 0.2
  MultiQuit= ; KillQQ= ; AnotherQQ=
  CurrentQQ_FullLine= ; CurrentQQ_LastField= ; CurrentQQ= ; CurrentQQ_Parent= ;
  CurrentQQ="$$"
  CurrentQQ_FullLine="$$  $0"
  CurrentQQ_Parent="$(ps --no-header -fo ppid "$CurrentQQ" | tr -cd '[:digit:]')"

  if [[ $ShowProcesses ]]; then
    [[ $CurrentQQ ]] && printf "\n    CurrentQQ = %s" "$CurrentQQ"
    [[ $CurrentQQ_Parent ]] && printf "    CurrentQQ_Parent = %s" "$CurrentQQ_Parent"
    printf "\n\n"
    printf "\n\n    POST find pid/ppid > pgrep -afi '/qqX' > \n\n"
    pgrep -afi '/qqX'
  fi

  # NOTE use 'ps' here as pgrep can cause problems
  # shellcheck disable=SC2009
  AnotherQQ="$(ps -ef | grep -e '/qqx' -e '/qqX' | grep -v 'qqX_copy_over' | grep -v 'qqX/tags' | grep -v '_install' | grep -v grep  2>/dev/null)"

  # If loading up the qcow menu, but then not choosing the qf option,
  # then the currrent qcow ceases to be a duplicate, and we need the VM selector interface, not the main selected one
  if [[ $Trace_InputVars ]]; then
    printf "\n\n Positional Vars = %s" "$*"
    printf "\n\n QF_exit_to_Main is %s" "$QF_exit_to_Main"
    printf "\n\n XDG_MimeType_is_QCOW is %s" "$XDG_MimeType_is_QCOW"
    printf "\n\n XDG_Input_NON_qqX is %s \n\n" "$XDG_Input_NON_qqX"
    echo " pwd  $(pwd)"
    echo; sleep "$Trace_InputVars"
  fi

  # CL launched running of qcow2 file management happens before this script is called. See qqX start.
  # Running CL instances will show up with 'pgrep -aAxi qqX' as 'pid /bin/bash /usr/bin/qqX --qqf' or similar
  # With pgrep -afi qqX_filemanage as: pid /bin/bash /usr/share/qqX/qqX.main/qqX_filemanage_qcow_drive --qqf

  if [[ $ShowProcesses ]]; then
    echo; echo " AnotherQQ String List:"; [[ $AnotherQQ ]] && printf "\n%s" "$AnotherQQ"
    printf "\n\n QF_exit_to_Main = %s \n\n" "$QF_exit_to_Main"
  fi

  CurrentQQ_mode="main"
  if [[ ! $QF_exit_to_Main ]]; then
    # qcow, in the sense of manage a qcow disk, not just use one trigger a main menu ...
    case "$CurrentQQ_LastField" in
      *'.qcow2'*|*'--qqf'*|*'qqX_filemanage '*) CurrentQQ_mode="qcow" ;;
    esac
  fi

  # Starting Main via the .qcow2 route needs to counted too. And only 1 QF instance should exist.
  # .qcow2 remains when 'exit to main' but changes to 'filemanage' when switching to QF
  # while elif [[ "$QQ" == *'.qcow2'* ]]; gets included in [[ "$QQ" != *'qqX_copy_over'* ]]

  if [[ $AnotherQQ ]]; then
    # NB: awk '{print $1}' for pgrep and awk '{print $2}' for ps
    OtherQQ_MainArr=()
    OtherQQ_qqF_Arr=()
    mapfile -t AnotherQQ_Arr <<< "$AnotherQQ"
    for QQ in "${AnotherQQ_Arr[@]}"; do
      [[ "$QQ" == *"$CurrentQQ"* ]] || [[ "$QQ" == *"$CurrentQQ_Parent"* ]] && continue
      [[ "$QQ" == *'/usr/'* ]] && [[ "$QQ" != *'/usr/share/qqX'* ]] && [[ "$QQ" != *'/usr/bin/qqX'* ]] && continue
      if [[ "$QQ" == *'--qqf'* ]] || [[ "$QQ" == *'qqX_filemanage'* ]]; then
        OtherQQ_qqF_Arr+=("$(awk '{print $2}' <<< "$QQ")")
      elif [[ "$QQ" != *'qqX_copy_over'* ]]; then
        [[ $QF_exit_to_Main ]] && QF_exit_to_Main=
        OtherQQ_MainArr+=("$(awk '{print $2}' <<< "$QQ")")
      fi
    done

    if [[ $ShowProcesses ]]; then
      [[ $CurrentQQ ]] && printf "\n CurrentQQ = %s" "$CurrentQQ"
      [[ $CurrentQQ_Parent ]] && printf "    CurrentQQ_Parent = %s" "$CurrentQQ_Parent"
      printf "\n\n"
      echo; declare -p AnotherQQ_Arr; echo
      echo; declare -p OtherQQ_MainArr; echo
      echo; declare -p OtherQQ_qqF_Arr; echo
      echo; echo " CurrentQQ_mode= $CurrentQQ_mode"; echo
      read -rp " >  "
    fi
  fi

  if [[ $CurrentQQ_mode == "main" ]] && [[ "${#OtherQQ_MainArr[@]}" -ge 1 ]]; then

    [[ $ShowProcesses ]] && printf "\n\n qqX_UI_chrome_up > Messaging and Options > Current Process PID: %s" "$CurrentQQ"

    qqX_logo_printf_title  "CAUTION: more than one instance of qqX appears to be running "
    printf "\n"
    printf "\n\n  QEMU will lock protect key files and will prevent VM's being run simultaneously"
    printf "\n\n  but be aware that minor cross-linking problems can occur, even if simple multi-instance usage is still possible "
    printf "\n\n  OR, this may just be a false alarm ..."
    printf "\n\n\n  [enter] to continue with all   [k] kill other instances and continue with just this one "
    printColor "\n\n  [q] to quit \n\n"
    read -rp "  >  "   MultiQuit

    [[ $MultiQuit == "q" ]] && exit directly

    if [[ $MultiQuit == "k" ]]; then
      if [[ $(pgrep kvm 2>/dev/null) ]]; then printColor "\n\n  CAUTION: Check for distros that may be running. Force closing can corrupt VM file systems ...."
      else
        printf "\n\n  Killing desktop started instances will close the terminal windows."
        printf "\n\n  CLI instances will terminate but the windows will remain open ..."
        printColor "\n\n\n  Killing other qqX instances ... "
      fi
      printf "\n\n  [k] yes, kill   [enter] continue with all   [q] to quit \n\n"
      read -rp "  >  "  KillQQ
      if [[ $KillQQ == "k" ]]; then
        for QQ in "${OtherQQ_MainArr[@]}"; do
          KillTarget="$(tr -cd '[:digit:]' <<< "$QQ"  2>/dev/null)"
          [[ $ShowProcesses ]] && printf "\n QQ = %  > killing: %s" "$QQ" "$KillTarget"
          [[ $KillTarget ]] &&  kill "$KillTarget" 2>/dev/null
        done
        printColor "\n\n  Closed  \n\n" ; sleep 0.7
      elif [[ $KillQQ == "q" ]]; then exit directly
      fi
    fi

  fi

  if [[ $ShowProcesses ]]; then
    echo; echo "Script: qqX_UI_chrome_up - end of function 'MULTI_INSTANCE_CHECKS' > "
    if [[ ${AnotherQQ_Arr[0]} ]]; then echo; declare -p AnotherQQ_Arr; echo; else printf "\n\n 'AnotherQQ_Arr' not present"; fi
    if [[ ${OtherQQ_MainArr[0]} ]]; then echo; declare -p OtherQQ_MainArr; echo; else printf "\n\n 'OtherQQ_MainArr' not present"; fi
    if [[ ${OtherQQ_qqF_Arr[0]} ]]; then echo; declare -p OtherQQ_qqF_Arr; echo; else printf "\n\n 'OtherQQ_qqF_Arr' not present"; fi
    printf "\n\n  CurrentQQ = %s\n\n" "$CurrentQQ"
    printf "\n\n  CurrentQQ_mode = %s\n\n" "$CurrentQQ_mode"
    read -rp " >  "
  fi

  if [[ "$(pgrep quickgui 2>/dev/null)" ]] ; then

    printColor "\n\n  WARNING: an instance of QUICKGUI appears to be running "
    printf "\n\n  Both this program and qqX do have an amount of cross-link protection, however note that:"
    printf "\n\n  Stopping an instance shown as running in QuickGUI may stop an instance started in qqX. \n\n"
    read -rp "  [q] to quit    [enter] to continue  > "   MultiQuit

    [[ $MultiQuit == "q" ]] && exit directly

  fi

  printf "" > "$ConfClearanceLog"

}
