#!/usr/bin/env bash

#  qqX project: early stage translation add-ins for the system_install script

##  Copyright (c)  Alex Genovese   https://github.com/qqxproject
#   SMALL CODE SNIPPETS eg the function printColor MAY BE USED
#   PERMISSIVELY in projects as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.

# 	Otherwise:

# Licence  GPL3   https://www.gnu.org/licenses

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# https://www.gnu.org/licenses

# IF CODE IN GENERAL BECOMES USED IN ANY OTHER PROJECT,
# THE GPL3 LICENCE APPLIES & YOU SHOULD SHOW CLEAR ATTRIBUTIONS.

# shellcheck disable=SC1090,SC2034,SC2154

find_web_browser() {
	WebBrowser="$(xdg-settings get default-web-browser 2>/dev/null)"
	if [[ $WebBrowser ]]; then XDG_Web=1 ; else XDG_Web=
	fi
	WebBrowser="${WebBrowser/'.desktop'/}"
	if [[ "$WebBrowser" == *'firefox'* ]]; then WebBrowser="firefox"
	elif [[ "$WebBrowser" == *'falkon'* ]]; then WebBrowser="falkon"
	elif [[ $(type -p 'google-chrome') ]]; then  WebBrowser="google-chrome"
	elif [[ $(type -p falkon) ]]; then  WebBrowser="falkon"
	elif [[ $(type -p midori) ]]; then  WebBrowser="midori"
	elif [[ $XDG_Web ]]; then WebBrowser="xdg-open"
	else WebBrowser=
	fi
}

find_translation_lang() {
	TxLang= ; SystemLang=
	# Use these for lookups, given https://cloud.google.com/translate/docs/languages#automl
	# And that @ 2025, the following have DIRECT PAIR Google data files:
	Iso_639_1_List="af ar az bg bn ca cs cy da de el en es et fa fi fr gl gu hi hr ht hu id is it ja ka ko lt lv mr ms nl no pa pl pt "
	Iso_639_1_List+="ro ru sk sl sq sr sv sw th tr uk ur vi zh"
	# Note, this normally includes zh-TW, but as standard zh is official in TW, just use zh > See https://en.wikipedia.org/wiki/Taiwan
	if grep -qs  "${LANG:0:2}" <<< "$Iso_639_1_List"; then SystemLang="${LANG:0:2}"
	elif grep -qs  "${GDM_LANG:0:2}" <<< "$Iso_639_1_List"; then SystemLang="${GDM_LANG:0:2}"
	elif grep -qs  "${LANGUAGE:0:2}" <<< "$Iso_639_1_List"; then SystemLang="${LANGUAGE:0:2}"
	fi
	# And where 'en' has been added for grep purposes as TxLang must be non-original (non en), otherwise Google complains
	[[ ! $SystemLang ]] && SystemLang="en"
	[[ $SystemLang == "en" ]] && TxLang="it"
	# And where caps vars are from std env
	if [[ ! $TxLang ]]; then
		if grep -qs  "${LANG:0:2}" <<< "$Iso_639_1_List"; then TxLang="${LANG:0:2}"
		elif grep -qs  "${GDM_LANG:0:2}" <<< "$Iso_639_1_List"; then TxLang="${GDM_LANG:0:2}"
		elif grep -qs  "${LANGUAGE:0:2}" <<< "$Iso_639_1_List"; then TxLang="${LANGUAGE:0:2}"
		fi
	fi
	# If not present in list, set to something known to work
	[[ ! $TxLang ]] && TxLang="it"
}

find_translate_text() {
	grep -A 500 TxTxt=\""$1"\" "$(pwd)/qqX.system/translate.from.english.txt" | grep -m 1 -B 500 'TxTxt_End' \
	| grep "${TxLang}=" | cut -d '=' -f 2- | tr -d '"' 2>/dev/null
}

open_installer_tx_screens_in_browser() {
	local OpenTx1="[enter] for Google auto-translate of installation text using"
	local OpenTx2="Unable to locate a Web Browser, which is needed for Google translation"
	local OpenTx3="to go back, more help is available at:"
	local OpenTx4="Opening Translated qqX Installation notes in Browser"
	local OpenTx5="ERROR: Browser or WebPages not found"
	if [[ $SystemLang != "en" ]] && [[ $TxLang ]]; then
		OpenTx1="$(find_translate_text "$OpenTx1")"
		OpenTx2="$(find_translate_text "$OpenTx2")"
		OpenTx3="$(find_translate_text "$OpenTx3")"
		OpenTx4="$(find_translate_text "$OpenTx4")"
		OpenTx5="$(find_translate_text "$OpenTx5")"
	fi
	if [[ $WebBrowser ]]; then
		printColor "\n\n  %s %s " "$OpenTx1" "$WebBrowser"
	else
		printColor "\n\n  %s" "$OpenTx2"
	fi
	printf "\n\n  [b] %s \"https://qqxproject.org/docs/Translation\" \n\n" "$OpenTx3"
	read -rp "  >  "  TxSetCode
	if [[ ! $TxSetCode ]]; then
		printf "\n  %s ... \n\n" "$OpenTx4"
		(nohup &> /dev/null  "$WebBrowser" "https://qqxproject-org.translate.goog/docs/Translation/Installation-menus?_x_tr_sl=auto&_x_tr_tl=${TxLang}&_x_tr_hl=en&_x_tr_pto=wapp"  & ) \
		|| printf "\n\n  %s \n\n" "$OpenTx5"
		sleep 1
	else
		TxSetCode= ; return
	fi
}
